/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, matchPrecache } from 'workbox-precaching';
import { registerRoute, NavigationRoute, setCatchHandler } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { BackgroundSyncPlugin } from 'workbox-background-sync';
import * as navigationPreload from 'workbox-navigation-preload';

declare const self: ServiceWorkerGlobalScope;

// Take control immediately
self.skipWaiting();
clientsClaim();

// Enable navigation preload
navigationPreload.enable();

// Precache all assets generated by build
precacheAndRoute(self.__WB_MANIFEST);

// Background Sync for offline expense submissions
const bgSyncPlugin = new BackgroundSyncPlugin('expense-queue', {
  maxRetentionTime: 24 * 60, // Retry for up to 24 hours
  onSync: async ({ queue }) => {
    let entry: any;
    while ((entry = await queue.shiftRequest())) {
      try {
        await fetch(entry.request);
        console.log('Background sync: Request successful', entry.request.url);

        await self.registration.showNotification('Expense Synced', {
          body: 'Your offline expense has been synced successfully!',
          icon: '/only-logo.png',
          badge: '/only-logo.png',
          tag: 'expense-sync'
        });
      } catch (error) {
        console.error('Background sync: Request failed', error);
        await queue.unshiftRequest(entry);
        throw error;
      }
    }
  }
});

// Cache API GET requests with StaleWhileRevalidate for instant UI
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/') && !url.pathname.includes('/auth/'),
  new StaleWhileRevalidate({
    cacheName: 'api-get-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 24 * 60 * 60 })
    ]
  }),
  'GET'
);

// Register background sync for POST API calls
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-post-cache',
    plugins: [bgSyncPlugin]
  }),
  'POST'
);

// Cache images with CacheFirst
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60,
      }),
    ],
  })
);

// Cache fonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60,
      }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);

// ROBUST NAVIGATION FALLBACK: Serve index.html for all navigation requests
const navigationHandler = async (params: any) => {
  try {
    // Attempt network first for navigation
    return await new NetworkFirst({
      cacheName: 'pages-cache',
      plugins: [new CacheableResponsePlugin({ statuses: [0, 200] })]
    }).handle(params);
  } catch (error) {
    // Fallback to precached index.html if network fails
    return (await matchPrecache('/index.html')) || Response.error();
  }
};

registerRoute(new NavigationRoute(navigationHandler));

// Global catch handler for failed requests
setCatchHandler(async ({ request }) => {
  if (request.destination === 'document') {
    return (await matchPrecache('/index.html')) || Response.error();
  }
  return Response.error();
});

// Periodic Background Sync
self.addEventListener('periodicsync', (event: any) => {
  if (event.tag === 'check-expenses') {
    event.waitUntil(checkForNewExpenses());
  }
});

async function checkForNewExpenses() {
  try {
    const response = await fetch('/api/check-new-expenses');
    const data = await response.json();
    if (data.hasNew) {
      await self.registration.showNotification('New Expense Added', {
        body: `${data.count} new expense(s) in your groups`,
        icon: '/only-logo.png',
        badge: '/only-logo.png',
        tag: 'new-expense',
        data: { url: '/activity' }
      });
    }
  } catch (error) {
    console.error('Periodic sync failed:', error);
  }
}

// Message handler for manual sync / UI interaction
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SYNC_EXPENSES') {
    event.waitUntil(
      (async () => {
        try {
          await self.registration.sync.register('expense-queue');
          if (event.ports[0]) event.ports[0].postMessage({ success: true });
        } catch (error) {
          if (event.ports[0]) event.ports[0].postMessage({ success: false, error });
        }
      })()
    );
  }

  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
